
-- TABLE CREATION


CREATE TABLE PRODUCTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    ENTRY_DATE DATE,
    BRAND VARCHAR(50),
    STOCK_AVAILABLE INT NOT NULL
);

CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    REGISTRATION_DATE DATE NOT NULL
);

CREATE TABLE PAYMENT_METHODS (
    METHOD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    METHOD_TYPE VARCHAR(50) NOT NULL,
    BANK_NAME VARCHAR(100)
);

CREATE TABLE REVIEWS (
    REVIEW_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUCT_CODE BIGINT NOT NULL,
    COMMENT TEXT NOT NULL,
    RATING INT NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    DATE_REVIEW DATE NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE INVOICES (
    INVOICE_NUMBER INTEGER PRIMARY KEY AUTOINCREMENT,
    PURCHASE_DATE DATE NOT NULL,
    BUYER_EMAIL VARCHAR(100) NOT NULL,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    USER_ID BIGINT NOT NULL,
    PAYMENT_METHOD_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHODS(METHOD_ID)
);

CREATE TABLE INVOICE_PRODUCTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    INVOICE_NUMBER BIGINT NOT NULL,
    PRODUCT_CODE BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (INVOICE_NUMBER) REFERENCES INVOICES(INVOICE_NUMBER),
    FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(ID)
);

CREATE TABLE SHOPPING_CART (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BUYER_EMAIL VARCHAR(100) NOT NULL,
    PRODUCT_CODE BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(ID)
);

-- ALTER TABLE (Step 3)

ALTER TABLE INVOICES ADD COLUMN BUYER_PHONE VARCHAR(20);
ALTER TABLE INVOICES ADD COLUMN CASHIER_CODE BIGINT;

-- TEST DATA INSERTION

INSERT INTO PRODUCTS (NAME, PRICE, ENTRY_DATE, BRAND, STOCK_AVAILABLE)
VALUES ('Laptop Dell Inspiron', 650000.00, '2026-01-15', 'Dell', 12);

INSERT INTO PRODUCTS (NAME, PRICE, ENTRY_DATE, BRAND, STOCK_AVAILABLE)
VALUES ('Mouse Inalámbrico', 8500.00, '2026-02-10', 'Logitech', 45);

INSERT INTO PRODUCTS (NAME, PRICE, ENTRY_DATE, BRAND, STOCK_AVAILABLE)
VALUES ('Teclado Mecánico', 35000.00, '2026-02-20', 'Redragon', 20);

INSERT INTO PRODUCTS (NAME, PRICE, ENTRY_DATE, BRAND, STOCK_AVAILABLE)
VALUES ('Monitor 24 pulgadas', 145000.00, '2026-03-01', 'Samsung', 8);

INSERT INTO USERS (FULL_NAME, EMAIL, REGISTRATION_DATE)
VALUES ('Ana Rodríguez', 'ana.rodriguez@email.com', '2025-11-05');

INSERT INTO USERS (FULL_NAME, EMAIL, REGISTRATION_DATE)
VALUES ('Carlos Jiménez', 'carlos.jimenez@email.com', '2025-12-12');

INSERT INTO USERS (FULL_NAME, EMAIL, REGISTRATION_DATE)
VALUES ('María Fernández', 'maria.fernandez@email.com', '2026-01-20');

INSERT INTO PAYMENT_METHODS (METHOD_TYPE, BANK_NAME)
VALUES ('Tarjeta de Crédito', 'BAC Credomatic');

INSERT INTO PAYMENT_METHODS (METHOD_TYPE, BANK_NAME)
VALUES ('Tarjeta de Débito', 'Banco Nacional');

INSERT INTO PAYMENT_METHODS (METHOD_TYPE, BANK_NAME)
VALUES ('Efectivo', NULL);

INSERT INTO PAYMENT_METHODS (METHOD_TYPE, BANK_NAME)
VALUES ('Transferencia SINPE', 'Banco Popular');

INSERT INTO REVIEWS (PRODUCT_CODE, COMMENT, RATING, DATE_REVIEW, USER_ID)
VALUES (2, 'Excelente mouse, muy cómodo', 5, '2026-03-10', 1);

INSERT INTO REVIEWS (PRODUCT_CODE, COMMENT, RATING, DATE_REVIEW, USER_ID)
VALUES (3, 'excelente', 5, '2026-05-23', 2);

INSERT INTO REVIEWS (PRODUCT_CODE, COMMENT, RATING, DATE_REVIEW, USER_ID)
VALUES (4, 'Buena resolución pero un poco caro', 3, '2026-04-02', 3);

INSERT INTO INVOICES (PURCHASE_DATE, BUYER_EMAIL, TOTAL_AMOUNT, USER_ID, PAYMENT_METHOD_ID, BUYER_PHONE, CASHIER_CODE)
VALUES ('2026-03-15', 'ana.rodriguez@email.com', 658500.00, 1, 1, '8888-1234', 101);

INSERT INTO INVOICES (PURCHASE_DATE, BUYER_EMAIL, TOTAL_AMOUNT, USER_ID, PAYMENT_METHOD_ID, BUYER_PHONE, CASHIER_CODE)
VALUES ('2026-04-02', 'carlos.jimenez@email.com', 35000.00, 2, 3, '8777-5566', 102);

INSERT INTO INVOICES (PURCHASE_DATE, BUYER_EMAIL, TOTAL_AMOUNT, USER_ID, PAYMENT_METHOD_ID, BUYER_PHONE, CASHIER_CODE)
VALUES ('2026-04-10', 'maria.fernandez@email.com', 145000.00, 3, 4, '8666-9988', 101);

INSERT INTO INVOICE_PRODUCTS (INVOICE_NUMBER, PRODUCT_CODE, QUANTITY, TOTAL_AMOUNT)
VALUES (1, 2, 1, 8500.00);

INSERT INTO INVOICE_PRODUCTS (INVOICE_NUMBER, PRODUCT_CODE, QUANTITY, TOTAL_AMOUNT)
VALUES (2, 3, 1, 35000.00);

INSERT INTO INVOICE_PRODUCTS (INVOICE_NUMBER, PRODUCT_CODE, QUANTITY, TOTAL_AMOUNT)
VALUES (3, 4, 1, 145000.00);

INSERT INTO SHOPPING_CART (BUYER_EMAIL, PRODUCT_CODE, QUANTITY)
VALUES ('ana.rodriguez@email.com', 1, 1);

INSERT INTO SHOPPING_CART (BUYER_EMAIL, PRODUCT_CODE, QUANTITY)
VALUES ('carlos.jimenez@email.com', 2, 2);

INSERT INTO SHOPPING_CART (BUYER_EMAIL, PRODUCT_CODE, QUANTITY)
VALUES ('maria.fernandez@email.com', 3, 1);

-- SELECT QUERIES (Step 4)

-- 1. All stored products
SELECT * FROM PRODUCTS;

-- 2. Products with a price greater than 50000
SELECT * FROM PRODUCTS WHERE PRICE > 50000;

-- 3. All purchases of the same product by id
SELECT * FROM INVOICE_PRODUCTS WHERE PRODUCT_CODE = 2;

-- 4. Purchases grouped by product, showing the total quantity purchased
SELECT PRODUCT_CODE, SUM(QUANTITY) AS TOTAL_PURCHASED
FROM INVOICE_PRODUCTS
GROUP BY PRODUCT_CODE;

-- 5. All invoices made by the same buyer
SELECT * FROM INVOICES WHERE BUYER_EMAIL = 'ana.rodriguez@email.com';

-- 6. All invoices ordered by total amount, descending
SELECT * FROM INVOICES ORDER BY TOTAL_AMOUNT DESC;

-- 7. A single invoice by invoice number
SELECT * FROM INVOICES WHERE INVOICE_NUMBER = 2;