CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_PHONE VARCHAR(20) NOT NULL
);

CREATE TABLE ITEMS (
    ITEM_ID INTEGER PRIMARY KEY,
    ITEM_NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE ORDERS (
    ORDER_ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    ADDRESS VARCHAR(150) NOT NULL,
    DELIVERY_TIME TIME NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE ORDER_ITEMS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ORDER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    QUANTITY INT NOT NULL,
    SPECIAL_REQUEST VARCHAR(150),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID)
);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_PHONE) VALUES (1, 'Alice', '123-456-7890');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_PHONE) VALUES (2, 'Bob', '987-654-3210');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_PHONE) VALUES (3, 'Claire', '555-123-4567');

INSERT INTO ITEMS (ITEM_ID, ITEM_NAME, PRICE) VALUES (101, 'Cheeseburger', 8.00);
INSERT INTO ITEMS (ITEM_ID, ITEM_NAME, PRICE) VALUES (102, 'Fries', 3.00);
INSERT INTO ITEMS (ITEM_ID, ITEM_NAME, PRICE) VALUES (103, 'Pizza', 12.00);
INSERT INTO ITEMS (ITEM_ID, ITEM_NAME, PRICE) VALUES (105, 'Salad', 6.00);
INSERT INTO ITEMS (ITEM_ID, ITEM_NAME, PRICE) VALUES (106, 'Water', 1.00);

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ADDRESS, DELIVERY_TIME) VALUES (1, 1, '123 Main St', '18:00');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ADDRESS, DELIVERY_TIME) VALUES (2, 2, '456 Elm St', '19:30');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ADDRESS, DELIVERY_TIME) VALUES (3, 3, '789 Oak St', '12:00');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ADDRESS, DELIVERY_TIME) VALUES (4, 3, '464 Georgia St', '17:00');

INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID, QUANTITY, SPECIAL_REQUEST) VALUES (1, 101, 2, 'No onions');
INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID, QUANTITY, SPECIAL_REQUEST) VALUES (1, 102, 1, 'Extra ketchup');
INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID, QUANTITY, SPECIAL_REQUEST) VALUES (2, 103, 1, 'Extra cheese');
INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID, QUANTITY, SPECIAL_REQUEST) VALUES (2, 102, 2, 'None');
INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID, QUANTITY, SPECIAL_REQUEST) VALUES (3, 105, 1, 'No croutons');
INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID, QUANTITY, SPECIAL_REQUEST) VALUES (4, 106, 1, 'None');

select * from CUSTOMERS;
select * from ITEMS;
select * from ORDERS;   

select * from ORDER_ITEMS;

